module.exports = {
  'nigeria': 'NG',
  'nigerian': 'NG',
  'ghana': 'GH',
  'ghanaian': 'GH',
  'kenya': 'KE',
  'kenyan': 'KE',
  'south africa': 'ZA',
  'south african': 'ZA',
  'angola': 'AO',
  'angolan': 'AO',
  'ethiopia': 'ET',
  'ethiopian': 'ET',
  'egypt': 'EG',
  'egyptian': 'EG',
  'tanzania': 'TZ',
  'tanzanian': 'TZ',
  'uganda': 'UG',
  'ugandan': 'UG',
  'cameroon': 'CM',
  'cameroonian': 'CM',
  'senegal': 'SN',
  'senegalese': 'SN',
  'ivory coast': 'CI',
  'côte d\'ivoire': 'CI',
  'benin': 'BJ',
  'beninese': 'BJ',
  'togo': 'TG',
  'togolese': 'TG',
  'mali': 'ML',
  'malian': 'ML',
  'niger': 'NE',
  'nigerien': 'NE',
  'burkina faso': 'BF',
  'zimbabwe': 'ZW',
  'zimbabwean': 'ZW',
  'zambia': 'ZM',
  'zambian': 'ZM',
  'rwanda': 'RW',
  'rwandan': 'RW',
  'mozambique': 'MZ',
  'mozambican': 'MZ',
  'madagascar': 'MG',
  'united states': 'US',
  'usa': 'US',
  'american': 'US',
  'united kingdom': 'GB',
  'uk': 'GB',
  'britain': 'GB',
  'british': 'GB',
  'france': 'FR',
  'french': 'FR',
  'germany': 'DE',
  'german': 'DE',
  'india': 'IN',
  'indian': 'IN',
  'china': 'CN',
  'chinese': 'CN',
  'brazil': 'BR',
  'brazilian': 'BR',
  'canada': 'CA',
  'canadian': 'CA',
  'australia': 'AU',
  'australian': 'AU',
  'japan': 'JP',
  'japanese': 'JP',
  'mexico': 'MX',
  'mexican': 'MX',
  'indonesia': 'ID',
  'indonesian': 'ID',
  'pakistan': 'PK',
  'pakistani': 'PK',
  'bangladesh': 'BD',
  'bangladeshi': 'BD',
};